version: '3.9'

volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  public:
    driver: overlay
  private:
    driver: overlay
    attachable: true

services:
  wordpress:
    depends_on:
      - mariadb
    image: docker.io/bitnami/wordpress-nginx:5.9.3-debian-10-r55
    networks:
      - public
      - private
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_PASSWORD=bitnami
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    deploy:
      replicas: 1

  mariadb:
    image: docker.io/bitnami/mariadb:10.6.8-debian-10-r10
    networks:
      - private
    volumes:
    - 'mariadb_data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_wordpress
    deploy:
      replicas: 1